<hr width="100%" style="border: 4px dashed #A1AFED" color="#FFFFFF" size="6">
<img src="<?php echo $pluginurl ?>../images/Need-Help.png" alt="help-button"><br><br>Below you will find the top 5 questions in our FAQ. Maybe they can help you in the right direction.	
<ul class="ul-square"><li><a href="https://www.dreamfoxmedia.com/knowledge-base/plugin-not-working?utm_source=plugin&utm_medium=faq_link&utm_campaign=dfm-wcpgpp-f" target="_blank">The plugin is not working.</a></li>
                    </ul><br>If your answer can not be found in the resources listed above, please use our support form on <a href="https://www.dreamfoxmedia.com/support-request-free-plugins?utm_source=plugin&utm_medium=supform_link&utm_campaign=dfm-wcpgpp-f" target="_blank">Dreamfoxmedia.com</a>
